import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juan Jose Bernal V :: Test Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <div className="footer__container">
          <h1 className="footer__title">Due credits for artwork used on this page</h1>
          <h2 className="footer__subtitle">Animation made by </h2>
          <a className="footer__link" target="_blank" href="https://lottiefiles.com/matheus.mesk?page=2">Matheus Mesquita</a>
          <h2 className="footer__subtitle">From</h2>
          <a className="footer__link" target="_blank" href="https://lottiefiles.com/">LottieFiles</a>
        </div>
      </body>
    </html>
  );
}
